// react-app/src/App.js
import React, { useEffect, useState } from 'react';
import io from 'socket.io-client';

const socket = io('http://localhost:3200'); // Connect to the server

function App() {
  const [name, setName] = useState('');

  useEffect(() => {
    // Function to send cursor position to the server
    const handleMouseMove = (event) => {
      const position = { x: event.clientX, y: event.clientY, name: 'React' };
      socket.emit('move cursor', position);
    };

    // Add event listener for mouse movement
    document.addEventListener('mousemove', handleMouseMove);

    // Listen for cursor moves from other users
    socket.on('move cursor', (position) => {
      const cursor = document.getElementById('cursor');
      if (cursor) {
        cursor.style.left = `${position.x}px`;
        cursor.style.top = `${position.y}px`;
        setName(position.name);
      }
    });

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      socket.off('move cursor');
    };
  }, []);

  return (
    <div>
      <h1>Cursor Tracker</h1>
      <div id="cursor" style={{ position: 'absolute', width: '10px', height: '10px', backgroundColor: 'red' }}>{name}</div>
    </div>
  );
}

export default App;

// angular/src/app/app.component.ts
import { Component, HostListener } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { io } from 'socket.io-client';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angular';
  private socket: any;
  public cursorStyle = { left: '0px', top: '0px', name: '' };

  ngOnInit(): void {
    this.socket = io('http://localhost:3200');

    this.socket.on('move cursor', (position: any) => {
      this.cursorStyle.left = `${position.x}px`;
      this.cursorStyle.top = `${position.y}px`;
      this.cursorStyle.name = `${position.name}`;
    });
  }

  @HostListener('document:mousemove', ['$event'])
  onMouseMove(event: MouseEvent) {
    this.socket.emit('move cursor', { x: event.clientX, y: event.clientY, name: 'Angular' });
  }
}

<h1>Angular Cursor Tracker</h1>
<div
  [style.position]="'absolute'"
  [style.width.px]="10"
  [style.height.px]="10"
  [style.backgroundColor]="'red'"
  [style.left]="cursorStyle.left"
  [style.top]="cursorStyle.top"
>
{{cursorStyle.name}}
</div>
